services:
  - type: web
    name: agas-api-staging
    runtime: docker
    plan: free
    region: virginia
    dockerfilePath: ./services/api/Dockerfile
    dockerContext: .
    autoDeployTrigger: commit
    healthCheckPath: /ready
    envVars:
      - key: AGAS_AUTH_MODE
        value: external
      - key: AGAS_CORS_ORIGINS
        value: '[]'
      - key: AGAS_DATABASE_URL
        sync: false
      - key: AGAS_ENVIRONMENT
        value: production
      - key: AGAS_EXTERNAL_AUTH_ALGORITHMS
        value: '["RS256"]'
      - key: AGAS_EXTERNAL_AUTH_AUDIENCE
        value: https://api.agas.staging
      - key: AGAS_EXTERNAL_AUTH_ISSUER
        sync: false
      - key: AGAS_EXTERNAL_AUTH_JWKS_URL
        sync: false
      - key: AGAS_MIGRATE_ON_STARTUP
        value: "true"
